<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="8" ignored="0" total="8" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_07_IST_2020error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_07_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_07_IST_2020error.jpg" height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg" height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg" height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_09_IST_2020error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_09_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_09_IST_2020error.jpg" height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg" height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg" height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_11_IST_2020error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_11_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_11_IST_2020error.jpg" height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_12_IST_2020error.jpg">Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_12_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_12_IST_2020error.jpg" height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Data Driven Framework" duration-ms="10951" started-at="2020-09-22T16:49:01Z" finished-at="2020-09-22T16:49:12Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="5618" started-at="2020-09-22T16:49:01Z" finished-at="2020-09-22T16:49:07Z">
      <class name="com.luna.testcases.BankManagerLoginTest">
        <test-method status="FAIL" signature="loginAsBankManager()[pri:0, instance:com.luna.testcases.BankManagerLoginTest@26e356f0]" name="loginAsBankManager" duration-ms="5078" started-at="2020-09-22T16:49:01Z" finished-at="2020-09-22T16:49:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Ayyoo testing!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Ayyoo testing!
at org.testng.Assert.fail(Assert.java:96)
at com.luna.testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_07_IST_2020error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_07_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_07_IST_2020error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- com.luna.testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="5320" started-at="2020-09-22T16:49:07Z" finished-at="2020-09-22T16:49:12Z">
      <class name="com.luna.testcases.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.luna.testcases.AddCustomerTest@5e600dd5]" name="setUp" is-config="true" duration-ms="2928" started-at="2020-09-22T16:48:59Z" finished-at="2020-09-22T16:49:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.luna.testcases.AddCustomerTest@5e600dd5]" name="addCustomer" duration-ms="524" started-at="2020-09-22T16:49:07Z" data-provider="getData" finished-at="2020-09-22T16:49:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Luna]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Love]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ty0071hg]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[everytime::]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: everytime::
at org.testng.Assert.fail(Assert.java:96)
at com.luna.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.luna.testcases.AddCustomerTest@5e600dd5]" name="addCustomer" duration-ms="208" started-at="2020-09-22T16:49:08Z" data-provider="getData" finished-at="2020-09-22T16:49:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Halo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Hulu]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[mndsi45s]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[everytime::]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: everytime::
at org.testng.Assert.fail(Assert.java:96)
at com.luna.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_08_IST_2020error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.luna.testcases.AddCustomerTest@5e600dd5]" name="addCustomer" duration-ms="193" started-at="2020-09-22T16:49:09Z" data-provider="getData" finished-at="2020-09-22T16:49:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Cosmo]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Cochi]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[mmnvu49]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[everytime::]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: everytime::
at org.testng.Assert.fail(Assert.java:96)
at com.luna.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_09_IST_2020error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_09_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_09_IST_2020error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.luna.testcases.AddCustomerTest@5e600dd5]" name="addCustomer" duration-ms="190" started-at="2020-09-22T16:49:10Z" data-provider="getData" finished-at="2020-09-22T16:49:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Misty]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Loovey]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[56bdj122]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[everytime::]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: everytime::
at org.testng.Assert.fail(Assert.java:96)
at com.luna.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.luna.testcases.AddCustomerTest@5e600dd5]" name="addCustomer" duration-ms="205" started-at="2020-09-22T16:49:10Z" data-provider="getData" finished-at="2020-09-22T16:49:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Onyx]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Cutie]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[hgn229cd]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[everytime::]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: everytime::
at org.testng.Assert.fail(Assert.java:96)
at com.luna.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_10_IST_2020error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.luna.testcases.AddCustomerTest@5e600dd5]" name="addCustomer" duration-ms="191" started-at="2020-09-22T16:49:11Z" data-provider="getData" finished-at="2020-09-22T16:49:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Kaiser]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Kaichu]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[837jnjc02]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[everytime::]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: everytime::
at org.testng.Assert.fail(Assert.java:96)
at com.luna.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_11_IST_2020error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_11_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_11_IST_2020error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.luna.testcases.AddCustomerTest@5e600dd5]" name="addCustomer" duration-ms="190" started-at="2020-09-22T16:49:12Z" data-provider="getData" finished-at="2020-09-22T16:49:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Notty]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Naughty]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[263002nc]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[everytime::]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: everytime::
at org.testng.Assert.fail(Assert.java:96)
at com.luna.testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_12_IST_2020error.jpg">Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="Screenshot_Tue_Sep_22_22_19_12_IST_2020error.jpg"><img src="Screenshot_Tue_Sep_22_22_19_12_IST_2020error.jpg" height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.luna.testcases.AddCustomerTest@5e600dd5]" name="tearDown" is-config="true" duration-ms="96" started-at="2020-09-22T16:49:12Z" finished-at="2020-09-22T16:49:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.luna.testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
  </suite> <!-- Data Driven Framework -->
</testng-results>
